name: Yuki(Harbinger)
url: https://github.com/Yesterday17/Yuki
description: やっぱり……いい女には、たばこと屋上と……そしてヒラヒラ服だわね……
public: false

default_events:
  - check_run
  - check_suite
  - issue_comment
  - issues
  - label
  - pull_request
  - pull_request_review
  - pull_request_review_comment

default_permissions:
  checks: write
  contents: write
  issues: write
  metadata: read
  pull_requests: write
  statuses: write
